### PR TITLE
fix: update carousel implementation

### PR DESCRIPTION
**Pull request by mchandak29**
Test URLs:
- Before: https://main--express-dev--nawaz-adobe.hlx.page/content/screens/express/40469c11-4c0d-4b0b-2efc-ad694126f8d8
- After: https://enhanced-workflow--express-dev--nawaz-adobe.hlx.page/content/screens/express/40469c11-4c0d-4b0b-2efc-ad694126f8d8

video case: https://enhanced-workflow--express-dev--nawaz-adobe.hlx.page/content/screens/express/720e9555-41d8-4dac-ae8a-693dbec9d5ce

### CODE REVIEW

**Comment by mchandak29** [comment]
@nawaz-adobe , @sahil9001  - please take a look at this pr.
I have updated the carousel implementation as well as upgraded offline resource generator.
With these changes:
1. we omit showing black frame on player.
2. we remove the duplicated code (coming from previous version of offline resources generator.)
3. what you see on page preview is what you see on player

**Comment by sahil9001** [comment]
I'm not aware of this, did we decide to add sliding carousel animation to the slides? or just direct switch?

**Comment by nawaz-adobe** [comment]
@mchandak29 why the sliding transition?

IIRC we wanted to add all the image source tags in HTML initially itself and then show/hide as needed.. wasn't that enough to fix the black screen in between?

**Comment by mchandak29** [comment]
@sahil9001 / @nawaz-adobe  -  I forgot to change the transition time. please take a look again.

**Comment by nawaz-adobe** [comment]
> @sahil9001 / @nawaz-adobe - I forgot to change the transition time. please take a look again.

@mchandak29 looks good now, but can you please clarify if we are using transitions here? and what's the use of transition time?

**Comment by sahil9001** [comment]
> > @sahil9001 / @nawaz-adobe - I forgot to change the transition time. please take a look again.
> 
> @mchandak29 looks good now, but can you please clarify if we are using transitions here? and what's the use of transition time?

I think because of this [issue](https://stackoverflow.com/a/53502551)

**Comment by mchandak29** [comment]
please see the doc explaining this carousel implementation - https://github.com/hlxscreens/cec-screens/blob/main/docs/carousel.md

I added the transition property to control how we want to translate from one slide to another. In this project, we want it really fast(and instantaneous), hence the 0.01s transition time.
As pointed out by sahil, it helps us explicitly specify how we want to transition instead of implicit definition by browsers

**Review by sahil9001 — APPROVED** [review]

**Comment by mchandak29** [comment]
@sahil9001 - where are we generating the word document for express channels?
we will need to make one change and include a page-metadata "Template=carousel"

**Comment by sahil9001** [comment]
> @sahil9001 - where are we generating the word document for express channels? we will need to make one change and include a page-metadata "Template=carousel"

We are doing that from backend now, you can find it [here](https://git.corp.adobe.com/Screens/screens-cloud-channel-io/pull/858/files#diff-d57721601a07963eb7eabe440dde953a516c71bee355bc491611d361bd847b19R1)

**Comment by sahil9001** [comment]
@mchandak29 can you close this as it is already merged in my repo? Also, this has been implemented in the Express Template repo here as well : https://github.com/hlxscreens/express-template/tree/main

**Comment by sahil9001** [comment]
closing this as it has many unresolvable conflicts

**Comment by habansal** [comment]
Replaced by https://github.com/nawaz-adobe/express-dev/pull/3

**Pull request closed without merging**
